import { Video, Creator, CreditPack } from "@/types";

export const mockCreators: Creator[] = [
  {
    id: "1",
    username: "nollywoodai",
    displayName: "Nollywood AI",
    isVerified: true,
    tier: "pro",
    followers: 128400,
    bio: "AI-powered Nollywood scenes & stories",
  },
  {
    id: "2",
    username: "lagosmotion",
    displayName: "Lagos Motion",
    isVerified: true,
    tier: "creator",
    followers: 45200,
  },
  {
    id: "3",
    username: "afroanime",
    displayName: "AfroAnime Labs",
    isVerified: false,
    tier: "free",
    followers: 8900,
  },
  {
    id: "4",
    username: "pidgintales",
    displayName: "Pidgin Tales",
    isVerified: true,
    tier: "pro",
    followers: 67300,
  },
];

export const mockVideos: Video[] = [
  {
    id: "v1",
    title: "The King Returns – Episode 1",
    description: "AI-generated Nollywood drama. The lost king returns to Lagos.",
    thumbnailUrl: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400&h=700&fit=crop",
    videoUrl: "",
    duration: 48,
    views: 284000,
    likes: 19200,
    comments: 843,
    earnings: 142000,
    category: "narrative",
    creator: mockCreators[0],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    isAIGenerated: true,
    tags: ["nollywood", "drama", "ai"],
  },
  {
    id: "v2",
    title: "Lagos Traffic in Anime Style",
    description: "What if Danfo buses were in a Studio Ghibli world?",
    thumbnailUrl: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&h=700&fit=crop",
    videoUrl: "",
    duration: 22,
    views: 156000,
    likes: 12800,
    comments: 421,
    earnings: 78000,
    category: "animation",
    creator: mockCreators[2],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    isAIGenerated: true,
    tags: ["anime", "lagos", "comedy"],
  },
  {
    id: "v3",
    title: "Yoruba Folklore: The Tortoise & the Birds",
    description: "Classic tale reimagined with modern AI animation.",
    thumbnailUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&h=700&fit=crop",
    videoUrl: "",
    duration: 95,
    views: 98000,
    likes: 8700,
    comments: 312,
    earnings: 52000,
    category: "cultural",
    creator: mockCreators[3],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    isAIGenerated: true,
    tags: ["folklore", "yoruba", "story"],
  },
  {
    id: "v4",
    title: "Afrobeats Visualizer – Burna Style",
    description: "High-energy AI motion graphics set to imaginary Afrobeats.",
    thumbnailUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=700&fit=crop",
    videoUrl: "",
    duration: 35,
    views: 412000,
    likes: 34100,
    comments: 1205,
    earnings: 210000,
    category: "music",
    creator: mockCreators[1],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    isAIGenerated: true,
    tags: ["afrobeats", "visualizer", "music"],
  },
  {
    id: "v5",
    title: "How AI is Changing Nollywood",
    description: "Educational short explaining the new wave of AI filmmaking in Nigeria.",
    thumbnailUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=700&fit=crop",
    videoUrl: "",
    duration: 180,
    views: 67000,
    likes: 4200,
    comments: 189,
    earnings: 34000,
    category: "educational",
    creator: mockCreators[0],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    isAIGenerated: true,
    tags: ["education", "nollywood", "ai"],
  },
  {
    id: "v6",
    title: "Street Comedy – Mama Put vs Customer",
    description: "Classic Lagos street comedy, fully AI generated.",
    thumbnailUrl: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=400&h=700&fit=crop",
    videoUrl: "",
    duration: 41,
    views: 198000,
    likes: 15600,
    comments: 987,
    earnings: 99000,
    category: "comedy",
    creator: mockCreators[3],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    isAIGenerated: true,
    tags: ["comedy", "lagos", "pidgin"],
  },
];

export const creditPacks: CreditPack[] = [
  { id: "p1", credits: 50, priceNgn: 2500, label: "Starter", priceUsdc: 1.5 },
  { id: "p2", credits: 150, priceNgn: 6500, label: "Creator", popular: true, priceUsdc: 4 },
  { id: "p3", credits: 400, priceNgn: 15000, label: "Pro", priceUsdc: 9 },
  { id: "p4", credits: 1000, priceNgn: 32000, label: "Studio", priceUsdc: 19 },
];
